apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-hub-api
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: ecommerce-hub-api
  template:
    metadata:
      labels:
        app: ecommerce-hub-api
    spec:
      containers:
        - name: ecommerce-hub-api
          image: {{ .Values.api.image }}
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: {{ .Values.env.dbHost | quote }}
            - name: RABBITMQ_HOST
              value: {{ .Values.env.dbHost | quote }}
            - name: REDIS_HOST
              value: {{ .Values.env.dbHost | quote }}
            - name: DB_USERNAME
              value: {{ .Values.env.dbUsername | quote }}
            - name: DB_PASSWORD
              value: {{ .Values.env.dbPassword | quote }}
            - name: JWT_SECRET
              value: {{ .Values.env.jwtSecret | quote }}