apiVersion: v1
kind: Service
metadata:
  name: ecommerce-hub-api
spec:
  type: NodePort
  selector:
    app: ecommerce-hub-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: {{ .Values.api.nodePort }}