apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-hub-worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: ecommerce-hub-worker
  template:
    metadata:
      labels:
        app: ecommerce-hub-worker
    spec:
      containers:
        - name: ecommerce-hub-worker
          image: {{ .Values.worker.image }}
          imagePullPolicy: Never
          env:
            - name: DB_HOST
              value: {{ .Values.env.dbHost | quote }}
            - name: RABBITMQ_HOST
              value: {{ .Values.env.dbHost | quote }}
            - name: REDIS_HOST
              value: {{ .Values.env.dbHost | quote }}
            - name: DB_USERNAME
              value: {{ .Values.env.dbUsername | quote }}
            - name: DB_PASSWORD
              value: {{ .Values.env.dbPassword | quote }}
            - name: DISCORD_WEBHOOK_URL
              value: {{ .Values.env.discordWebhookUrl | quote }}